import mongoose, { Schema, model, models } from 'mongoose';

const DocumentSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    content: {
      type: String, // Plain text extracted from document
      required: true,
    },
    summary: {
      type: String, // Summary generated by Claude API
    },
    analysis: {
      type: String, // Analysis or key points generated by Claude API
    },
    fileType: {
      type: String,
      default: 'txt',
    },
    size: {
      type: Number, // Bytes
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

const Document = models.Document || model('Document', DocumentSchema);
export default Document;
